server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: course-service-public
          uri: http://localhost:8082
          predicates:
            - Path=/api/public/**

        - id: course-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/courses/**

        - id: registration-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/registrations/**

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration